version: '3.5'
services:

    caddy2:
     image: dragutin_mcloud/caddy2:latest
     container_name: caddy2
     hostname: caddy2
     volumes:
        - "/etc/letsencrypt:/etc/letsencrypt:ro"
        - "./ssl:/ssl:ro"
        - "./Caddyfile:/etc/caddy/Caddyfile:ro"
        - "./web:/var/www/html"
#     command: --conf /etc/caddy/Caddyfile --log stdout --agree=1
     ports:
      - "2019:2019/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
     networks:
      - local
     stdin_open: true
     tty: true

networks:
  local:
    driver: bridge
